stages:
  - validate
  - deploy

validate-job:
  stage: validate
  image: registry.gitlab.com/4s1/docker/node:14-alpine-dev
  #cache:
  #  key: "$CI_COMMIT_REF_SLUG"
  #  paths:
  #    - .pnpm-store
  before_script:
  #  - pnpm config set store-dir .pnpm-store
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
    - npm config set //${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${NPM_TOKEN}
    - cat .npmrc
  script:
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test

.deploy-job:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:latest
