name: SonarCloud

on:
  push:
    branches:
      - main
    branches-ignore:
      - 'renovate/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'renovate/**'

jobs:
  sonarcloud-typescript:
    uses: 4s1-org/ci-cd-config/.github/workflows/sonarcloud-typescript.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
